services:
  - type: web
    name: facenova-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: RAZORPAY_KEY_ID
        value: ""
      - key: RAZORPAY_KEY_SECRET
        value: ""
